# Generated by Django 4.1.7 on 2023-03-06 20:56

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import videos.models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='video',
            field=models.FileField(default=django.utils.timezone.now, upload_to='media/videofiles/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mkv']), videos.models.validate_file_size]),
            preserve_default=False,
        ),
    ]
